# **Numpy Part1**

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
myarr = np.array(mylist)

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
my_matirx = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_matirx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matirx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,2)

array([[0.63443938, 0.7778642 ],
       [0.78172031, 0.75298569],
       [0.24171599, 0.14740618],
       [0.31424199, 0.25164241],
       [0.77956416, 0.23241486]])

In [ ]:
np.random.randn(10)

array([-1.3557766 ,  2.05308424, -1.15022777,  0.94588256, -0.63958255,
       -1.11220594,  0.98091098, -1.07148137, -1.65457135, -0.71168347])

In [ ]:
np.random.randn(2,3)

array([[ 0.38800978, -0.7542966 , -1.02163451],
       [-0.37388082, -0.53382686, -0.20990654]])

In [ ]:
np.random.randint(0,101,(4,5))

array([[ 7,  2, 14, 47, 67],
       [93, 76,  3, 18, 94],
       [17, 90, 94, 92, 27],
       [67,  8, 99,  0, 14]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
array = np.arange(0,25)

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
randarr = np.random.randint(0,101,10)


In [ ]:
randarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
randarr.max()

99

In [ ]:
randarr.min()

2

In [ ]:
randarr.argmax()

5

In [ ]:
randarr.argmin()

7

In [ ]:
randarr.dtype

dtype('int64')

In [ ]:
randarr.shape

(10,)

In [ ]:
array.shape

(25,)

In [ ]:
array = array.reshape(5,5)

In [ ]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
array.shape

(5, 5)

# **Numpy Part 2**

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[0,2]

15

In [ ]:
arr_2d[:-1,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# **Numpy Part 3**

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-106-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr

<ipython-input-107-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-110-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])